name: Infer
on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
    paths:
      - .github/workflows/infer.yaml

jobs:
  scan:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install infer
        run: brew install infer
      - name: Run Infer
        run: |
          git diff --name-only origin/feature..origin/main > index.txt
          infer capture -- ./gradlew build
          infer analyze --fail-on-issue --eradicate --changed-files-index ./index.txt
          
